name: Snyk CLI Scans

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  snyk-pipeline:
    runs-on: ubuntu-latest
    name: Snyk SAST
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:      
      - uses: actions/checkout@v2
      - name: Install & Auth Snyk
        run: |
          curl https://static.snyk.io/cli/latest/snyk-linux -o snyk
          chmod +x ./snyk
          snyk auth ${SNYK_TOKEN}
      - name: Run Snyk
        run: |
          snyk code test      
        continue-on-error: true
