name: Snyk Code Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sast-scan:
    runs-on: ubuntu-latest
    name: Snyk Code Scan
    steps:      
      - uses: actions/checkout@v2
      - uses: snyk/actions/setup@master
      - name: Snyk Code Test
        run: snyk code test --sarif-file-output=snyk_sast_results.json
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          
      # Upload results    
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk_sast_results.json
      
      
 


