name: Snyk Vuln Count

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sca-scan:
    runs-on: ubuntu-latest
    name: Get vuln count
    steps:      
      - uses: actions/checkout@v2
      - uses: snyk/actions/setup@master
      - name: Snyk Test
        run: |
          npm install          
          echo "::set-output name=vulncount::$(snyk test --json | jq '.uniqueCount')"
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          
      - name: Vuln Count badge
        uses: RubbaBoy/BYOB@v1.2.1
        with:
          NAME: vulncount
          LABEL: 'Vulnerabilities'
          STATUS: ${{ env.vulncount }}
          COLOR: red
